import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import cn from 'classnames'

import "./globals.css";
import Nav from "./_components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {

  return (
    <html lang="en" className="w-full h-full" suppressHydrationWarning>
      <body className={cn(inter.className, 'w-full h-full')}>
        <ThemeProvider attribute="class">
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;